# Generated by Django 5.2.15 on 2026-09-20 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_workspace_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_id', models.UUIDField(blank=True, null=True)),
                ('file_name_snapshot', models.CharField(max_length=255)),
                ('version_no', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('upload_initiated', 'Upload initiated'), ('upload_completed', 'Upload completed'), ('upload_failed', 'Upload failed'), ('version_created', 'Version created'), ('version_activated', 'Version activated'), ('downloaded', 'Downloaded'), ('previewed', 'Previewed'), ('renamed', 'Renamed'), ('moved', 'Moved'), ('copied', 'Copied'), ('linked', 'Linked'), ('unlinked', 'Unlinked'), ('trashed', 'Trashed'), ('restored', 'Restored'), ('purged', 'Purged'), ('permission_denied', 'Permission denied'), ('quota_rejected', 'Quota rejected')], max_length=32)),
                ('actor_display', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'File Access Log',
                'verbose_name_plural': 'File Access Logs',
                'db_table': 'file_access_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_normalized', models.CharField(max_length=255)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'File Folder',
                'verbose_name_plural': 'File Folders',
                'db_table': 'file_folders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_type', models.CharField(choices=[('verify', 'Verify'), ('thumbnail', 'Thumbnail'), ('scan', 'Scan'), ('extract', 'Extract'), ('purge', 'Purge'), ('usage_recompute', 'Usage recompute')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File Job',
                'verbose_name_plural': 'File Jobs',
                'db_table': 'file_jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('issue', 'Issue'), ('page', 'Page'), ('comment', 'Comment'), ('milestone', 'Milestone'), ('deliverable', 'Deliverable')], max_length=24)),
                ('entity_id', models.UUIDField()),
                ('entity_identifier', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'File Link',
                'verbose_name_plural': 'File Links',
                'db_table': 'file_links',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_original', models.CharField(max_length=255)),
                ('name_display', models.CharField(max_length=255)),
                ('name_normalized', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=127)),
                ('extension', models.CharField(blank=True, default='', max_length=32)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('bucket', models.CharField(max_length=63)),
                ('object_key', models.CharField(max_length=1024, unique=True)),
                ('category', models.CharField(choices=[('_system', 'System'), ('docs', 'Docs'), ('issues', 'Issues'), ('pages', 'Pages'), ('deliverables', 'Deliverables'), ('assets', 'Assets'), ('imports', 'Imports'), ('exports', 'Exports'), ('archive', 'Archive')], default='assets', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded_unverified', 'Uploaded unverified'), ('active', 'Active'), ('failed', 'Failed'), ('quarantined', 'Quarantined'), ('archived', 'Archived'), ('trashed', 'Trashed'), ('purge_failed', 'Purge failed'), ('purged', 'Purged')], default='pending', max_length=24)),
                ('visibility', models.CharField(choices=[('project', 'Project')], default='project', max_length=16)),
                ('current_version_no', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File Object',
                'verbose_name_plural': 'File Objects',
                'db_table': 'file_objects',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('version_no', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=1024, unique=True)),
                ('bucket', models.CharField(max_length=63)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(max_length=127)),
                ('client_checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('server_checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('magic_bytes_checked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('active', 'Active'), ('superseded', 'Superseded'), ('failed', 'Failed'), ('purged', 'Purged'), ('purge_failed', 'Purge failed')], default='uploading', max_length=24)),
                ('is_active', models.BooleanField(default=False)),
                ('storage_metadata', models.JSONField(default=dict)),
                ('reserved_bytes', models.BigIntegerField(default=0)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('object_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'File Version',
                'verbose_name_plural': 'File Versions',
                'db_table': 'file_versions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectStorageUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('limit_bytes', models.BigIntegerField(blank=True, null=True)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('reserved_bytes', models.BigIntegerField(default=0)),
                ('version_count', models.PositiveIntegerField(default=0)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('recomputed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Storage Usage',
                'verbose_name_plural': 'Project Storage Usage',
                'db_table': 'project_storage_usage',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('limit_bytes', models.BigIntegerField(blank=True, null=True)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('reserved_bytes', models.BigIntegerField(default=0)),
                ('warn_threshold_pct', models.PositiveSmallIntegerField(default=80)),
                ('enforce', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Storage Quota',
                'verbose_name_plural': 'Storage Quotas',
                'db_table': 'storage_quotas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='retention_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='storage_key',
            field=models.CharField(blank=True, db_index=True, max_length=96, null=True),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('storage_key__isnull', False)), fields=('workspace', 'storage_key'), name='project_unique_storage_key_workspace_when_not_null'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_file_access_logs', to='db.project'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_access_logs', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.filefolder'),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='filejob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='filejob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='filejob',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='filejob',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='db.filefolder'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='db.fileobject'),
        ),
        migrations.AddField(
            model_name='filejob',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='db.fileobject'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='db.fileobject'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_file_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='filejob',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='db.fileversion'),
        ),
        migrations.AddField(
            model_name='projectstorageusage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='projectstorageusage',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to='db.project'),
        ),
        migrations.AddField(
            model_name='projectstorageusage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='storagequota',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='storagequota',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='storagequota',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to='db.workspace'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['project', 'created_at'], name='file_log_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['file_id', 'created_at'], name='file_log_file_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['actor', 'created_at'], name='file_log_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['action', 'created_at'], name='file_log_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['project', 'parent', 'name_normalized'], name='file_folder_proj_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='filefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'parent', 'name_normalized'), name='file_folder_unique_name_in_parent_when_deleted_at_null'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['project', 'folder', 'name_normalized'], name='file_obj_proj_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['project', 'status', 'created_at'], name='file_obj_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['project', 'mime_type'], name='file_obj_proj_mime_idx'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['project', 'created_by', 'created_at'], name='file_obj_proj_author_idx'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['project', 'size_bytes'], name='file_obj_proj_size_idx'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['workspace', 'project'], name='file_obj_workspace_proj_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileobject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('status', 'trashed'), _negated=True)), fields=('project', 'folder', 'name_normalized'), name='file_object_unique_name_in_folder_when_live'),
        ),
        migrations.AddIndex(
            model_name='filelink',
            index=models.Index(fields=['project', 'entity_type', 'entity_id'], name='file_link_proj_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='filelink',
            index=models.Index(fields=['file'], name='file_link_file_idx'),
        ),
        migrations.AddConstraint(
            model_name='filelink',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('file', 'entity_type', 'entity_id'), name='file_link_unique_file_entity_when_deleted_at_null'),
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['file', 'is_active'], name='file_version_file_active_idx'),
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['status', 'created_at'], name='file_version_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileversion',
            constraint=models.UniqueConstraint(fields=('file', 'version_no'), name='file_version_unique_file_version_no'),
        ),
        migrations.AddConstraint(
            model_name='fileversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('file',), name='file_version_unique_active_per_file'),
        ),
        migrations.AddConstraint(
            model_name='filejob',
            constraint=models.UniqueConstraint(condition=models.Q(('version__isnull', False)), fields=('version', 'job_type'), name='file_job_unique_version_job_type'),
        ),
        migrations.AddConstraint(
            model_name='filejob',
            constraint=models.UniqueConstraint(condition=models.Q(('job_type', 'purge')), fields=('file', 'job_type'), name='file_job_unique_file_purge'),
        ),
    ]
