# Generated by Django 5.2.15 on 2026-09-20 02:54

"""Harden the project-file constraints (T-101 verification F-01, F-02, F-07).

* The two name-uniqueness constraints gain ``nulls_distinct=False`` so they also
  cover the project root, where ``folder_id``/``parent_id`` are NULL and
  PostgreSQL would otherwise treat every row as distinct (PostgreSQL 15+).
* ``file_jobs`` verification uniqueness is narrowed to ``job_type='verify'`` so a
  failed thumbnail/scan job can be queued again; purge stays keyed by file.
* ``file_versions.status_changed_at`` becomes a mutable timestamp the sweep's age
  guard can rely on.
"""

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_backfill_project_storage_keys'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filefolder',
            name='file_folder_unique_name_in_parent_when_deleted_at_null',
        ),
        migrations.RemoveConstraint(
            model_name='filejob',
            name='file_job_unique_version_job_type',
        ),
        migrations.RemoveConstraint(
            model_name='fileobject',
            name='file_object_unique_name_in_folder_when_live',
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='filefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'parent', 'name_normalized'), name='file_folder_unique_name_in_parent_when_deleted_at_null', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='filejob',
            constraint=models.UniqueConstraint(condition=models.Q(('job_type', 'verify')), fields=('version', 'job_type'), name='file_job_unique_verify_per_version'),
        ),
        migrations.AddConstraint(
            model_name='fileobject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('status', 'trashed'), _negated=True)), fields=('project', 'folder', 'name_normalized'), name='file_object_unique_name_in_folder_when_live', nulls_distinct=False),
        ),
    ]
