# Generated by Django 5.2.15 on 2026-09-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_file_constraint_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccesslog',
            name='action',
            field=models.CharField(choices=[('upload_initiated', 'Upload initiated'), ('upload_completed', 'Upload completed'), ('upload_failed', 'Upload failed'), ('version_created', 'Version created'), ('version_activated', 'Version activated'), ('downloaded', 'Downloaded'), ('previewed', 'Previewed'), ('renamed', 'Renamed'), ('moved', 'Moved'), ('copied', 'Copied'), ('linked', 'Linked'), ('unlinked', 'Unlinked'), ('trashed', 'Trashed'), ('restored', 'Restored'), ('purged', 'Purged'), ('permission_denied', 'Permission denied'), ('quota_rejected', 'Quota rejected'), ('folder_created', 'Folder created'), ('folder_renamed', 'Folder renamed'), ('folder_moved', 'Folder moved'), ('folder_deleted', 'Folder deleted')], max_length=32),
        ),
    ]
