# Generated by Django 5.2.15 on 2026-09-30 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0130_filecopycleanup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfluenceSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("site_url", models.URLField(max_length=255)),
                ("space_id", models.CharField(max_length=100)),
                ("space_name", models.CharField(blank=True, max_length=255)),
                ("access", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confluence_destinations",
                        to="db.page",
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.project")),
                (
                    "root",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confluence_sources",
                        to="db.page",
                    ),
                ),
            ],
            options={
                "db_table": "confluence_sources",
            },
        ),
        migrations.CreateModel(
            name="ConfluenceRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("mode", models.CharField(default="changed", max_length=16)),
                ("selection", models.JSONField(default=list)),
                ("status", models.CharField(default="queued", max_length=20)),
                ("phase", models.TextField(default="Waiting for worker")),
                ("inventory_complete", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="db.confluencesource"
                    ),
                ),
            ],
            options={
                "db_table": "confluence_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfluenceItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=16)),
                ("remote_id", models.CharField(max_length=100)),
                ("category", models.CharField(default="page", max_length=100)),
                ("title", models.TextField(blank=True)),
                ("remote", models.JSONField(default=dict)),
                ("imported_version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.fileobject"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confluence_item_folders",
                        to="db.page",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confluence_items",
                        to="db.page",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="db.confluencesource"
                    ),
                ),
            ],
            options={
                "db_table": "confluence_items",
            },
        ),
        migrations.CreateModel(
            name="ConfluenceRunItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("version", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="db.confluenceitem"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="db.confluencerun"
                    ),
                ),
            ],
            options={
                "db_table": "confluence_run_items",
                "constraints": [models.UniqueConstraint(fields=("run", "item"), name="confluence_run_item_unique")],
            },
        ),
        migrations.AddConstraint(
            model_name="confluencesource",
            constraint=models.UniqueConstraint(
                fields=("project", "site_url", "space_id"), name="confluence_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="confluencerun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "discovering", "running"])),
                fields=("source",),
                name="confluence_one_active_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="confluenceitem",
            constraint=models.UniqueConstraint(fields=("source", "kind", "remote_id"), name="confluence_item_unique"),
        ),
    ]
