# Generated by Django 5.2.15 on 2026-10-02 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0131_confluence_import_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("site_url", models.URLField(max_length=255)),
                ("remote_project_id", models.CharField(max_length=100)),
                ("project_key", models.CharField(max_length=100)),
                ("project_name", models.CharField(max_length=255)),
                ("user_mapping", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.project")),
            ],
            options={
                "db_table": "jira_sources",
            },
        ),
        migrations.CreateModel(
            name="JiraRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("mode", models.CharField(default="changed", max_length=16)),
                ("selection", models.JSONField(default=list)),
                ("status", models.CharField(default="queued", max_length=20)),
                ("phase", models.TextField(default="Waiting for worker")),
                ("inventory_complete", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="db.jirasource"
                    ),
                ),
            ],
            options={
                "db_table": "jira_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JiraItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=16)),
                ("remote_id", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("title", models.TextField(blank=True)),
                ("remote", models.JSONField(default=dict)),
                ("imported_revision", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.issuecomment"),
                ),
                ("cycle", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.cycle")),
                (
                    "file",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.fileobject"),
                ),
                ("issue", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.issue")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="db.jirasource"
                    ),
                ),
            ],
            options={
                "db_table": "jira_items",
            },
        ),
        migrations.CreateModel(
            name="JiraRunItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("revision", models.CharField(max_length=64)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("warning", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="db.jiraitem"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="db.jirarun"
                    ),
                ),
            ],
            options={
                "db_table": "jira_run_items",
                "constraints": [models.UniqueConstraint(fields=("run", "item"), name="jira_run_item_unique")],
            },
        ),
        migrations.AddConstraint(
            model_name="jirasource",
            constraint=models.UniqueConstraint(
                fields=("project", "site_url", "remote_project_id"), name="jira_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="jirarun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "discovering", "running"])),
                fields=("source",),
                name="jira_one_active_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="jiraitem",
            constraint=models.UniqueConstraint(fields=("source", "kind", "remote_id"), name="jira_item_unique"),
        ),
    ]
